//  Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	fmt "fmt"

	devicev1alpha1 "github.com/nvidia/nvsentinel/client-go/client/versioned/typed/device/v1alpha1"
	nvgrpc "github.com/nvidia/nvsentinel/client-go/nvgrpc"
	grpc "google.golang.org/grpc"
)

type Interface interface {
	DeviceV1alpha1() devicev1alpha1.DeviceV1alpha1Interface
}

// Clientset contains the clients for groups.
type Clientset struct {
	deviceV1alpha1 *devicev1alpha1.DeviceV1alpha1Client
}

// DeviceV1alpha1 retrieves the DeviceV1alpha1Client
func (c *Clientset) DeviceV1alpha1() devicev1alpha1.DeviceV1alpha1Interface {
	return c.deviceV1alpha1
}

// NewForConfig creates a new Clientset for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, clientConn),
// where clientConn was generated with nvgrpc.ClientConnFor(c).
//
// If you need to customize the connection (e.g. set a logger),
// use nvgrpc.ClientConnFor() manually and pass the connection to NewForConfigAndClient.
func NewForConfig(c *nvgrpc.Config) (*Clientset, error) {
	if c == nil {
		return nil, fmt.Errorf("config cannot be nil")
	}

	configShallowCopy := *c // Shallow copy to avoid mutation
	conn, err := nvgrpc.ClientConnFor(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	return NewForConfigAndClient(&configShallowCopy, conn)
}

// NewForConfigAndClient creates a new Clientset for the given config and gRPC client connection.
// The provided gRPC client connection provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *nvgrpc.Config, conn grpc.ClientConnInterface) (*Clientset, error) {
	if c == nil {
		return nil, fmt.Errorf("config cannot be nil")
	}
	if conn == nil {
		return nil, fmt.Errorf("gRPC connection cannot be nil")
	}

	configShallowCopy := *c // Shallow copy to avoid mutation

	var cs Clientset
	var err error
	cs.deviceV1alpha1, err = devicev1alpha1.NewForConfigAndClient(&configShallowCopy, conn)
	if err != nil {
		return nil, err
	}

	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config or connection setup.
func NewForConfigOrDie(c *nvgrpc.Config) *Clientset {
	cs, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return cs
}

// New creates a new Clientset for the given gRPC client connection.
func New(conn grpc.ClientConnInterface) *Clientset {
	var cs Clientset
	cs.deviceV1alpha1 = devicev1alpha1.New(conn)

	return &cs
}
